name: whisperx-web

services:
  whisperx_web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/srv/data
    environment:
      WHISPERX_MODEL: large-v3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: ["gpu"]
