<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Migrations/*.sql" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
  </ItemGroup>
</Project>

