using System.Speech.Synthesis;
using System.Globalization;
using System.Threading.Channels;
using NAudio.Wave;

namespace WhisperX.Atom.Voice.Host;

internal sealed record SpeechRequest(string Text, byte[]? Wav, TaskCompletionSource Completion);

public sealed class SpeechResponder : IDisposable
{
    private readonly SpeechSynthesizer _synthesizer = new();
    private readonly Dictionary<string, byte[]> _responses = new(StringComparer.OrdinalIgnoreCase);
    private readonly bool _usePreRecordedResponses;
    private readonly object _gate = new();
    private readonly Channel<SpeechRequest> _queue = Channel.CreateBounded<SpeechRequest>(new BoundedChannelOptions(8)
    {
        SingleReader = true,
        SingleWriter = false,
        FullMode = BoundedChannelFullMode.Wait
    });
    private readonly CancellationTokenSource _shutdown = new();
    private readonly Task _worker;
    private bool _disposed;
    private int _busy;
    private int _speaking;
    private bool _russianVoiceAvailable;

    public SpeechResponder()
    {
        // Runtime synthesis is the safe default. The original offline WAV
        // bundle was generated by Windows PowerShell 5.1 from a UTF-8 script
        // without a BOM and can therefore contain spoken mojibake instead of
        // the intended Russian phrase. Keep the bundle available only for an
        // explicitly validated deployment.
        _usePreRecordedResponses = ReadBooleanEnvironment("ATOM_VOICE_USE_PRERECORDED_RESPONSES");
        if (_usePreRecordedResponses)
        {
            var root = Path.Combine(AppContext.BaseDirectory, "Assets", "VoiceResponses");
            if (Directory.Exists(root))
                foreach (var file in Directory.EnumerateFiles(root, "*.wav"))
                    _responses[Path.GetFileNameWithoutExtension(file)] = File.ReadAllBytes(file);
        }

        // Prefer the deterministic Russian voice requested by the product.
        // Windows often exposes both "Microsoft Irina" and "Microsoft Irina
        // Desktop"; the desktop variant is a safe fallback, never an English
        // voice.  An explicit ATOM_VOICE_NAME remains useful for diagnostics.
        try
        {
            var installed = _synthesizer.GetInstalledVoices()
                .Where(voice => voice.Enabled)
                .Select(voice => voice.VoiceInfo)
                .ToArray();
            var requestedName = Environment.GetEnvironmentVariable("ATOM_VOICE_NAME");
            var russianVoice = installed.FirstOrDefault(voice => !string.IsNullOrWhiteSpace(requestedName)
                    && string.Equals(voice.Name, requestedName, StringComparison.OrdinalIgnoreCase)
                    && voice.Culture.Name.StartsWith("ru", StringComparison.OrdinalIgnoreCase))
                ?? installed.FirstOrDefault(voice => string.Equals(voice.Name, "Microsoft Irina", StringComparison.OrdinalIgnoreCase))
                ?? installed.FirstOrDefault(voice => string.Equals(voice.Name, "Microsoft Irina Desktop", StringComparison.OrdinalIgnoreCase))
                ?? installed.FirstOrDefault(voice => voice.Culture.Name.StartsWith("ru", StringComparison.OrdinalIgnoreCase));
            if (russianVoice is not null)
            {
                _synthesizer.SelectVoice(russianVoice.Name);
                _russianVoiceAvailable = true;
            }
        }
        catch (InvalidOperationException) { }
        catch (ArgumentException) { }
        _synthesizer.Rate = ReadIntEnvironment("ATOM_VOICE_RATE", 0, -10, 10);
        _synthesizer.Volume = ReadIntEnvironment("ATOM_VOICE_VOLUME", 90, 0, 100);
        _worker = Task.Run(ProcessAsync);
    }

    public bool QuietMode { get; set; }
    public bool UsesPreRecordedResponses => _usePreRecordedResponses;
    public string VoiceName
    {
        get
        {
            try { return _synthesizer.Voice.Name; }
            catch (InvalidOperationException) { return "Windows default"; }
        }
    }
    public string VoiceCulture
    {
        get
        {
            try { return _synthesizer.Voice.Culture.Name; }
            catch (InvalidOperationException) { return CultureInfo.CurrentUICulture.Name; }
        }
    }
    public bool ConfigureVoice(string? requestedName, int? rate, int? volume)
    {
        lock (_gate)
        {
            try
            {
                var installed = _synthesizer.GetInstalledVoices()
                    .Where(voice => voice.Enabled && voice.VoiceInfo.Culture.Name.StartsWith("ru", StringComparison.OrdinalIgnoreCase))
                    .Select(voice => voice.VoiceInfo)
                    .ToArray();
                var selected = !string.IsNullOrWhiteSpace(requestedName)
                    ? installed.FirstOrDefault(voice => string.Equals(voice.Name, requestedName.Trim(), StringComparison.OrdinalIgnoreCase))
                    : null;
                selected ??= installed.FirstOrDefault(voice => string.Equals(voice.Name, "Microsoft Irina", StringComparison.OrdinalIgnoreCase));
                selected ??= installed.FirstOrDefault(voice => string.Equals(voice.Name, "Microsoft Irina Desktop", StringComparison.OrdinalIgnoreCase));
                selected ??= installed.FirstOrDefault();
                if (selected is null)
                {
                    _russianVoiceAvailable = false;
                    return false;
                }
                _synthesizer.SelectVoice(selected.Name);
                _synthesizer.Rate = Math.Clamp(rate ?? _synthesizer.Rate, -10, 10);
                _synthesizer.Volume = Math.Clamp(volume ?? _synthesizer.Volume, 0, 100);
                _russianVoiceAvailable = true;
                return true;
            }
            catch (InvalidOperationException) { _russianVoiceAvailable = false; return false; }
            catch (ArgumentException) { _russianVoiceAvailable = false; return false; }
        }
    }
    public bool IsSpeaking => Volatile.Read(ref _speaking) != 0;
    public bool IsBusy => Volatile.Read(ref _busy) != 0;
    public event Action<Exception>? Error;

    public bool TryEnqueue(string text)
        => TryEnqueue(text, out _);

    public bool TryEnqueue(string text, out Task completion)
    {
        var completed = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        completion = completed.Task;
        if (_disposed || QuietMode || !_russianVoiceAvailable || string.IsNullOrWhiteSpace(text))
        {
            completed.TrySetResult();
            return false;
        }
        var key = ResponseKey(text);
        _responses.TryGetValue(key ?? string.Empty, out var wav);
        lock (_gate)
        {
            Volatile.Write(ref _busy, 1);
            if (_queue.Writer.TryWrite(new SpeechRequest(text, wav, completed))) return true;
            if (!_queue.Reader.TryPeek(out _)) Volatile.Write(ref _busy, 0);
            completed.TrySetResult();
            return false;
        }
    }

    private async Task ProcessAsync()
    {
        try
        {
            await foreach (var request in _queue.Reader.ReadAllAsync(_shutdown.Token))
            {
                try
                {
                    if (QuietMode) continue;
                    Volatile.Write(ref _speaking, 1);
                    if (request.Wav is not null) await PlayWavAsync(request.Wav, _shutdown.Token);
                    else await Task.Run(() => { lock (_gate) _synthesizer.Speak(request.Text); }, _shutdown.Token);
                }
                catch (OperationCanceledException) when (_shutdown.IsCancellationRequested) { break; }
                catch (Exception ex) { Error?.Invoke(ex); }
                finally
                {
                    Volatile.Write(ref _speaking, 0);
                    request.Completion.TrySetResult();
                    lock (_gate)
                    {
                        if (!_queue.Reader.TryPeek(out _)) Volatile.Write(ref _busy, 0);
                    }
                }
            }
        }
        catch (OperationCanceledException) when (_shutdown.IsCancellationRequested) { }
    }

    private static async Task PlayWavAsync(byte[] wav, CancellationToken cancellationToken)
    {
        using var memory = new MemoryStream(wav, writable: false);
        using var reader = new WaveFileReader(memory);
        using var output = new WaveOutEvent { DesiredLatency = 60 };
        var completion = new TaskCompletionSource(TaskCreationOptions.RunContinuationsAsynchronously);
        output.PlaybackStopped += (_, args) =>
        {
            if (args.Exception is null) completion.TrySetResult();
            else completion.TrySetException(args.Exception);
        };
        output.Init(reader);
        using var registration = cancellationToken.Register(output.Stop);
        output.Play();
        await completion.Task.WaitAsync(cancellationToken);
    }

    private static string? ResponseKey(string text)
    {
        if (text.Equals("Слушаю", StringComparison.OrdinalIgnoreCase)) return "listening";
        if (text.Equals("Запись начата", StringComparison.OrdinalIgnoreCase)) return "recording-started";
        if (text.Equals("Запись приостановлена", StringComparison.OrdinalIgnoreCase)) return "recording-paused";
        if (text.Equals("Запись продолжена", StringComparison.OrdinalIgnoreCase)) return "recording-resumed";
        if (text.Equals("Совещание завершено", StringComparison.OrdinalIgnoreCase)) return "recording-stopped";
        if (text.StartsWith("Метка", StringComparison.OrdinalIgnoreCase)) return "marker-added";
        if (text.StartsWith("Решение", StringComparison.OrdinalIgnoreCase)) return "decision-added";
        if (text.StartsWith("Поручение", StringComparison.OrdinalIgnoreCase)) return "action-added";
        if (text.StartsWith("Подтвердите остановку", StringComparison.OrdinalIgnoreCase)) return "confirmation-required";
        if (text.Contains("не распознана", StringComparison.OrdinalIgnoreCase) || text.Contains("недоступна", StringComparison.OrdinalIgnoreCase)) return "command-rejected";
        if (text.Contains("ошиб", StringComparison.OrdinalIgnoreCase) || text.StartsWith("Не удалось", StringComparison.OrdinalIgnoreCase)) return "error";
        return null;
    }

    private static bool ReadBooleanEnvironment(string name)
    {
        var value = Environment.GetEnvironmentVariable(name);
        return string.Equals(value, "1", StringComparison.OrdinalIgnoreCase)
            || string.Equals(value, "true", StringComparison.OrdinalIgnoreCase)
            || string.Equals(value, "yes", StringComparison.OrdinalIgnoreCase);
    }

    private static int ReadIntEnvironment(string name, int fallback, int minimum, int maximum)
        => int.TryParse(Environment.GetEnvironmentVariable(name), out var value)
            ? Math.Clamp(value, minimum, maximum)
            : fallback;

    public bool Test() => TryEnqueue("Голосовой помощник готов");

    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        _queue.Writer.TryComplete();
        _shutdown.Cancel();
        try { _worker.Wait(TimeSpan.FromSeconds(1)); } catch { }
        lock (_gate) _synthesizer.Dispose();
        _shutdown.Dispose();
    }
}
